import React, { createContext, useContext, useState, useEffect } from 'react'

export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', flag: '🌾' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🌴' },
]

export const CROPS_DATA = [
  {
    key: 'Wheat',
    icon: '🌾',
    names: { en: 'Wheat', hi: 'गेहूं', pa: 'ਕਣਕ', ta: 'கோதுமை' },
  },
  {
    key: 'Paddy',
    icon: '🌾',
    names: { en: 'Paddy', hi: 'धान', pa: 'ਝੋਨਾ', ta: 'நெல்' },
  },
  {
    key: 'Mustard',
    icon: '🌼',
    names: { en: 'Mustard', hi: 'सरसों', pa: 'ਸਰ੍ਹੋਂ', ta: 'கடுகு' },
  },
  {
    key: 'Maize',
    icon: '🌽',
    names: { en: 'Maize', hi: 'मक्का', pa: 'ਮੱਕੀ', ta: 'மக்காச்சோளம்' },
  },
  {
    key: 'Gram',
    icon: '🌱',
    names: { en: 'Gram', hi: 'चना', pa: 'ਛੋਲੇ', ta: 'கொண்டைக்கடலை' },
  },
  {
    key: 'Soybean',
    icon: '🫘',
    names: { en: 'Soybean', hi: 'सोयाबीन', pa: 'ਸੋਇਆਬੀਨ', ta: 'சோயாபீன்' },
  },
]

const translations = {
  en: {
    // Navbar
    kisanMandi: 'Kisan Mandi',
    eProcurement: 'E-Procurement',
    deptSubtitle: 'Dept of Consumer Affairs • Smart Procurement',
    registeredFarmer: 'Registered Farmer',
    farmer: 'Farmer',
    signOut: 'Sign Out',
    selectLanguage: 'Language',

    // Farmer Login & Registration
    backToHome: 'Back to Home',
    kisanPortal: 'Kisan Portal',
    farmerSignInTitle: 'Farmer Sign In',
    farmerSignInSubtitle: 'Sign in with your registered phone number via secure OTP',
    farmerRegisterTitle: 'Farmer Registration',
    farmerRegisterSubtitle: 'Register once to book mandi slots and receive MSP payments',
    tabSignIn: 'Farmer Sign In (OTP)',
    tabRegister: 'Register New Farmer',
    mobileNumberLabel: 'Mobile Number',
    mobileNumberPlaceholder: 'e.g. 9876543210',
    mobileNumberHelp: 'Enter the 10-digit mobile number linked with your PM-Kisan / Mandi account.',
    sendLoginOtp: 'Send Login OTP',
    sendingOtp: 'Sending OTP...',
    enterOtpLabel: 'Enter 6-Digit OTP',
    changeNumber: 'Change Number',
    verifyAndSignIn: 'Verify & Sign In',
    verifying: 'Verifying...',
    resendOtp: "Didn't receive OTP? Resend OTP",
    simulatedSmsCode: 'Simulated SMS Code',
    autoFilled: 'Auto-filled',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'e.g. Ramesh Kumar',
    villageDistrictLabel: 'Village / District',
    villageDistrictPlaceholder: 'e.g. Rampur, Anantnag',
    landRecordLabel: 'Land Record / Khasra',
    landRecordPlaceholder: 'e.g. KH-45892/2024',
    bankAccountLabel: 'Bank Account for DBT',
    bankAccountPlaceholder: 'e.g. 123456789012',
    registerAndContinue: 'Register & Continue',
    registering: 'Registering...',
    loginGovFooter: 'Ministry of Consumer Affairs, Food & Public Distribution • Direct Farmer MSP Portal',
    validPhoneError: 'Please enter a valid 10-digit mobile number.',
    farmerNotFoundError: 'No farmer found with this phone number. Please click "Register New Farmer" below.',
    otpSentSuccess: 'OTP sent to +91 {phone}. Please enter the 6-digit code.',
    validOtpError: 'Please enter the 6-digit OTP code.',
    signInSuccess: 'Signed in successfully! Redirecting to Kisan Dashboard...',
    registerRequiredFields: 'Please provide both your Name and Mobile Number.',
    registeredSuccess: 'Farmer registered successfully! Redirecting to your dashboard...',
    alreadyRegisteredPhone: 'This phone number is already registered. Please switch to "Farmer Sign In" above.',

    // Farmer Home
    kisanDashboard: 'Kisan Dashboard',
    welcomeGreeting: 'Namaste',
    homeSubtitle: 'Manage your scheduled mandi visits, avoid rush-hour waiting lines, and receive direct MSP payments in your bank account.',
    landRecordKhasra: 'Land Record / Khasra',
    verifiedLand: 'Verified Land',
    dbtBankLinked: 'DBT Bank Linked',
    active: 'Active',
    smsSimulationTitle: 'Simulated SMS Alert (DoCA-GOV)',
    smsDeliveredTo: 'Delivered to {phone} • Instant Queue Token',
    footerHackathon: 'Smart India Hackathon 2024 • Ministry of Consumer Affairs, Food & Public Distribution',
    footerPlatform: 'Smart Automation & Real-Time Procurement Platform',

    // Live Queue Tracker
    radarCompleted: 'Weighing Completed & Accepted',
    radarInYard: 'Live Mandi Yard Radar',
    radarPreArrival: 'Pre-Arrival Turn Radar',
    mandiCenterDefault: 'Mandi Procurement Center',
    completedTokenPrefix: 'Completed Token: ',
    inYardTokenPrefix: 'In-Yard Token: ',
    advanceTokenPrefix: 'Advance Token: ',
    updated: 'Updated',
    refreshQueue: 'Refresh Queue',
    activeTokensNotice: 'You have {count} Active Tokens:',
    weighedStatus: 'Weighed',
    inYardStatus: 'In Yard',
    bookedStatus: 'Booked',

    // Radar Cards - Scenario 1: Completed
    weighbridgeScale1: 'Electronic Weighbridge #1',
    weighedDone: 'Weighed Done',
    quintals: 'Quintals',
    kg: 'kg',
    produceWeighedVerified: 'Produce Weighed & Verified',
    qualityGrade: 'Quality Grade',
    officialMsp: 'Official MSP',
    totalMspPayout: 'Total MSP Payout',
    dbtDisbursed: 'DBT Disbursed',
    dbtQueued: 'DBT Queued',
    dbtPaidDesc: 'Payment disbursed directly into your linked bank account via Aadhaar DBT.',
    dbtQueuedDesc: 'Disbursement initiated. Government Treasury release expected within 24-48 hours.',

    // Radar Cards - Scenario 2: In Yard
    nowServingScale1: 'Now Serving at Scale #1',
    scaleServingBadge: 'Weighbridge Scale',
    scaleOpen: 'Scale Open',
    scaleTractorPositioned: 'Tractor currently positioned on electronic weighbridge scale',
    scaleOpenReady: 'Scale is open and ready for the next arrival',
    inYardPosition: 'In-Yard Position',
    yourTurnNow: 'Your Turn Now!',
    queuePos: 'Queue #{pos}',
    checkedInAtGate: 'Checked-In at Gate',
    driveScaleNow: 'Please drive your tractor onto Scale #1 now!',
    tractorsAheadYard: '{count} tractor{plural} ahead of you in yard line',
    gateVerifiedSync: 'Gate entry verified • Syncing with weighbridge dispatch...',

    // Radar Cards - Scenario 3: Pre-Arrival
    mandiScaleServing: 'Mandi Scale #1 Currently Serving',
    scaleOpenHome: 'Scale Open',
    processingNow: 'Processing Now',
    tractorsLinedUpYard: '{count} tractor{plural} currently lined up inside the mandi yard.',
    yourAdvanceBooking: 'Your Advance Booking',
    nextInTurn: 'Next in Turn',
    tokensAheadPreArrival: '{count} Tokens Ahead',
    estimatedScaleTurn: 'Estimated scale turn at ~{time} ({hours}h {mins}m)',
    tomorrowLabel: 'Tomorrow',
    scheduledSlotConfirmed: 'Scheduled Slot Confirmed',
    scheduledForTomorrow: 'Scheduled for Tomorrow',
    scheduledForDate: 'Scheduled for {date}',
    gateOpensTomorrowDesc: 'Gate security check-in opens at 9:00 AM tomorrow.',
    futureBookingNoticeTitle: 'Arrival Slot Confirmed for {date} at {time}',
    futureBookingNoticeBody: 'Please arrive at {center} on {date} with your loaded vehicle and land documents. Live queue radar will activate automatically tomorrow morning.',
    step2ArriveTomorrow: 'Arrive on {date} at {time}',
    gateCheckInPending: 'Gate Check-In Pending',
    turnNumberLabel: 'Turn #{num}',
    estimatedScaleTurnTime: 'Estimated Scale Turn',
    procurementHistory: 'Procurement History',
    viewWeighedTokens: 'Weighed Tokens',
    weighedTokensModalTitle: 'Weighed Tokens & Payment Status',
    weighedTokensModalSubtitle: 'Official weighbridge records and Direct Benefit Transfer (DBT) disbursement status',
    noWeighedTokensYet: 'No Weighed Tokens Yet',
    noWeighedTokensDesc: 'Once your produce is weighed at Mandi Dharamkanta scale #1, your verified weighment slip and DBT deposit record will appear here.',
    weighedOnDate: 'Weighed On',
    scheduledGateArrival: 'Suggested Gate Arrival',
    futureStaggeredNotice: 'Please reach Mandi Gate by ~{arrivalTime} for security check-in. Your estimated turn on Dharamkanta scale is ~{turnTime} (Turn #{turn}).',
    history: 'History',
    closeModal: 'Close',

    // Notices
    lunchBreakTitle: 'Mandi Lunch Break in Progress (1:00 PM – 2:00 PM)',
    lunchBreakDesc: 'Weighbridge scales are paused for official staff lunch. Scales and turn progression resume promptly at 2:00 PM.',
    resumesAtTwoPm: 'Resumes at 2:00 PM',
    gateClosedTitle: 'Mandi Gate Entry Closed for Today (5:00 PM)',
    gateClosedInYardDesc: 'Your tractor is inside the yard. Scale #1 is on duty to complete weighing for all checked-in vehicles.',
    gateClosedHomeDesc: 'Gate entry has closed for the day. Un-checked-in bookings are expired. Please book a slot for tomorrow.',
    gateClosedBadge: 'Gate Closed (5:00 PM)',

    // Advisories
    congratsWeighedTitle: 'Weighing Complete for Token {token}!',
    congratsWeighedBody: 'Your {crop} consignment has been weighed and accepted. Total MSP amount of ₹{amount} is registered for Direct Benefit Transfer (DBT){bankSuffix}.',
    bankAccountEnding: ' to your bank account ending in ••••{last4}',
    yardTurnNowTitle: 'It is your turn for {token}!',
    yardTurnNowBody: 'Drive your tractor onto Dharamkanta Scale #1 now. The weighbridge officer is ready for tare/gross weighing.',
    yardGetReadyTitle: 'Get ready for {token}!',
    yardGetReadyBody: 'Only {count} tractor{plural} ahead. Please start your tractor and stay near the weighbridge ramp.',
    yardRestShedTitle: 'Relax comfortably in the farmer rest shed!',
    yardRestShedBody: 'There are {count} tractors ahead in the yard. We will notify you when 5 tractors remain.',
    preArrivalUrgentTitle: 'Turn Approaching for {token}! Please Proceed to Gate',
    preArrivalUrgentBody: 'There are only {count} token{plural} ahead. Drive to {center} Gate #1 now to check in and join the scale queue.',
    preArrivalRelaxTitle: 'Relax at Home: Your Turn is Estimated at ~{time}',
    preArrivalRelaxBody: 'The scale is currently processing token {servingToken} with {ahead} tokens ahead of you today. Please arrive at the Mandi Gate 30 minutes before your turn (by ~{gateTime}) to check in.',
    earlierSlots: 'earlier slots',
    suggestedGateArrival: 'Suggested Gate Arrival',
    immediately: 'Immediately',

    // Traffic & Velocity
    yardTrafficTitle: 'Mandi Yard Traffic ({center})',
    fastFlow: 'Fast Flow',
    yardTrafficDesc: '{yardCount} tractor{yardPlural} currently in yard queue • {bookedCount} advance tokens scheduled today • Average scale time: ~{avgMin} mins',
    yardWaitTimeLabel: 'Yard Scale Wait Time',
    estimatedTimeToTurnLabel: 'Estimated Time to Turn',
    zeroMinsProcured: '0 mins (Procured)',
    zeroMinsAtScale: '0 mins (At Scale)',
    approxMinutes: '~{mins} minutes',
    approxMinsWithTime: '~{mins} mins (~{time})',

    // 5-Step Journey Stepper
    procurementLifecycle: 'Procurement Lifecycle for Token {token}',
    step1Title: 'Slot Booked',
    step1Subtitle: 'Confirmed',
    step2Title: 'Gate Check-In',
    step2EntryDone: 'Entry Done',
    step2CheckedIn: 'Checked In at Mandi',
    step2ReachGateNow: 'Reach Gate Now!',
    step2ArriveBy: 'Arrive by ~{time}',
    step3Title: 'Weighbridge Scale',
    step3WeighingDone: 'Weighing Done',
    step3NowAtScale1: 'Now at Scale #1',
    step3QueueNum: 'Queue #{pos}',
    step3InLine: 'In Line',
    step4Title: 'Produce Weighed',
    step4JFormIssued: 'J-Form Slip Issued',
    step4AwaitingScale: 'Awaiting Scale',
    step5Title: 'DBT Bank Payout',
    step5Credited: 'Credited to Bank',
    step5InTransit: 'DBT in Transit',
    step5DirectDeposit: 'Direct Deposit',
    stepNum: 'Step {num}',

    // Slot Booking
    smartSlotAllocation: 'Smart Slot Allocation',
    bookMandiArrivalSlot: 'Book Mandi Arrival Slot',
    slotBookingSubtitle: 'Reserve an arrival window to eliminate waiting line delays and receive your digital queue token',
    slotConfirmed: 'Slot Confirmed!',
    yourToken: 'Your Token:',
    smsSimulatedHint: 'SMS confirmation has been simulated. Show this token at the mandi counter on arrival.',
    bookAnotherSlot: 'Book Another Slot',
    mandiCenterLabel: 'Mandi Center',
    loadingCenters: 'Loading centers...',
    noCentersConfigured: 'No centers configured in backend yet.',
    produceCropLabel: 'Produce Crop',
    arrivalDateLabel: 'Arrival Date',
    availableSlotsForCrop: 'Available Arrival Slots for {crop}',
    slotsAvailableCount: '{count} {label} available',
    slotSingular: 'slot',
    slotPlural: 'slots',
    intakeCapacityFullTitle: "Today's Mandi Intake at Full Capacity",
    intakeCapacityFullDesc: 'Queue for today already extends past the 5:00 PM gate closing. Any further bookings for today cannot be accommodated.',
    switchToTomorrow: 'Switch to Tomorrow',
    checkingSlotAvailability: 'Checking real-time slot availability...',
    noOpenSlotsFound: 'No open slots found for this date & crop',
    noOpenSlotsDesc: 'The center administration may not have scheduled procurement hours for this combination yet. Try selecting another date or crop.',
    intakeClosedCutoff: 'Intake Closed (5 PM Cutoff)',
    slotFullBadge: 'Full',
    seatsLeftBadge: '{count} seats left',
    capacityBookedText: 'Capacity: {booked} / {capacity} farmers booked',
    reservingSeat: 'Reserving Seat...',
    intakeFullBtn: 'Intake Full (Cutoff 5:00 PM)',
    slotFullBtn: 'Slot Full',
    bookThisSlotBtn: 'Book This Slot',

    // Farmer History
    myTokensPassbook: 'My Tokens & Mandi Passbook',
    historySubtitle: 'View active arrival passes, counter progress, and DBT payment transfer status',
    refreshHistory: 'Refresh History',
    loadingPassbook: 'Loading your digital passbook...',
    noHistoryYet: 'No booking history yet',
    noHistoryDesc: "You haven't booked any mandi slots yet. Use the booking section above to reserve your first arrival window.",
    statusBooked: 'Booked',
    statusCheckedIn: 'In Mandi Queue',
    statusCompleted: 'Procured',
    statusCancelled: 'Cancelled',
    paymentAwaitingWeighing: 'Awaiting weighing',
    paymentPaidViaDbt: 'Paid via DBT',
    paymentProcessing: 'Processing',
    paymentPending: 'Payment Pending',
    tokenLabel: 'Token',
    atTime: 'at',
    cropLabel: 'Crop',
    cancelSlot: 'Cancel Slot',
    cancelling: 'Cancelling...',
    confirmCancelBooking: 'Are you sure you want to cancel this booking? The slot will be released back to other farmers.',
  },

  hi: {
    // Navbar
    kisanMandi: 'किसान मंडी',
    eProcurement: 'ई-उपार्जन',
    deptSubtitle: 'उपभोक्ता मामले विभाग • स्मार्ट खरीद प्रणाली',
    registeredFarmer: 'पंजीकृत किसान',
    farmer: 'किसान',
    signOut: 'लॉग आउट',
    selectLanguage: 'भाषा',

    // Farmer Login & Registration
    backToHome: 'मुख्य पृष्ठ पर वापस',
    kisanPortal: 'किसान पोर्टल',
    farmerSignInTitle: 'किसान लॉगिन',
    farmerSignInSubtitle: 'अपने पंजीकृत मोबाइल नंबर से सुरक्षित ओटीपी द्वारा लॉगिन करें',
    farmerRegisterTitle: 'नया किसान पंजीकरण',
    farmerRegisterSubtitle: 'मंडी स्लॉट बुक करने और सीधा एमएसपी भुगतान पाने हेतु एक बार पंजीकरण करें',
    tabSignIn: 'किसान लॉगिन (ओटीपी)',
    tabRegister: 'नया किसान पंजीकरण',
    mobileNumberLabel: 'मोबाइल नंबर',
    mobileNumberPlaceholder: 'उदा. 9876543210',
    mobileNumberHelp: 'अपने पीएम-किसान अथवा मंडी खाते से जुड़ा 10 अंकों का मोबाइल नंबर दर्ज करें।',
    sendLoginOtp: 'लॉगिन ओटीपी भेजें',
    sendingOtp: 'ओटीपी भेजा जा रहा है...',
    enterOtpLabel: '6 अंकों का ओटीपी दर्ज करें',
    changeNumber: 'नंबर बदलें',
    verifyAndSignIn: 'सत्यापित करें एवं लॉगिन करें',
    verifying: 'सत्यापन जारी है...',
    resendOtp: 'ओटीपी नहीं मिला? पुनः भेजें',
    simulatedSmsCode: 'सिम्युलेटेड एसएमएस कोड',
    autoFilled: 'स्वतः भरा गया',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'उदा. रमेश कुमार',
    villageDistrictLabel: 'गाँव / ज़िला',
    villageDistrictPlaceholder: 'उदा. रामपुर, अनंतनाग',
    landRecordLabel: 'खसरा / भूमि रिकॉर्ड',
    landRecordPlaceholder: 'उदा. KH-45892/2024',
    bankAccountLabel: 'डीबीटी बैंक खाता संख्या',
    bankAccountPlaceholder: 'उदा. 123456789012',
    registerAndContinue: 'पंजीकरण करें एवं आगे बढ़ें',
    registering: 'पंजीकरण जारी है...',
    loginGovFooter: 'उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय • सीधा किसान एमएसपी पोर्टल',
    validPhoneError: 'कृपया 10 अंकों का मान्य मोबाइल नंबर दर्ज करें।',
    farmerNotFoundError: 'इस नंबर से कोई किसान पंजीकृत नहीं है। कृपया नीचे "नया किसान पंजीकरण" पर क्लिक करें।',
    otpSentSuccess: '+91 {phone} पर ओटीपी भेजा गया है। कृपया 6 अंकों का कोड दर्ज करें।',
    validOtpError: 'कृपया 6 अंकों का ओटीपी कोड दर्ज करें।',
    signInSuccess: 'सफलतापूर्वक लॉगिन हो गया! किसान डैशबोर्ड पर पुनर्निर्देशित किया जा रहा है...',
    registerRequiredFields: 'कृपया अपना नाम और मोबाइल नंबर दोनों दर्ज करें।',
    registeredSuccess: 'किसान पंजीकरण सफल रहा! डैशबोर्ड पर पुनर्निर्देशित किया जा रहा है...',
    alreadyRegisteredPhone: 'यह मोबाइल नंबर पहले से पंजीकृत है। कृपया ऊपर "किसान लॉगिन" चुनें।',

    // Farmer Home
    kisanDashboard: 'किसान डैशबोर्ड',
    welcomeGreeting: 'नमस्ते',
    homeSubtitle: 'अपनी निर्धारित मंडी यात्रा का प्रबंधन करें, कतारों से बचें, और सीधे अपने बैंक खाते में एमएसपी भुगतान प्राप्त करें।',
    landRecordKhasra: 'खसरा / भूमि रिकॉर्ड',
    verifiedLand: 'सत्यापित भूमि',
    dbtBankLinked: 'डीबीटी बैंक खाता लिंक',
    active: 'सक्रिय',
    smsSimulationTitle: 'सिम्युलेटेड एसएमएस सूचना (DoCA-GOV)',
    smsDeliveredTo: '{phone} पर प्रेषित • डिजिटल कतार टोकन',
    footerHackathon: 'स्मार्ट इंडिया हैकथॉन 2024 • उपभोक्ता मामले, खाद्य और सार्वजनिक वितरण मंत्रालय',
    footerPlatform: 'स्मार्ट स्वचालन एवं वास्तविक समय खरीद प्लेटफॉर्म',

    // Live Queue Tracker
    radarCompleted: 'तौल संपन्न एवं स्वीकृत',
    radarInYard: 'लाइव मंडी यार्ड रडार',
    radarPreArrival: 'अग्रिम टोकन रडार',
    mandiCenterDefault: 'मंडी खरीद केंद्र',
    completedTokenPrefix: 'संपन्न टोकन: ',
    inYardTokenPrefix: 'यार्ड में टोकन: ',
    advanceTokenPrefix: 'अग्रिम टोकन: ',
    updated: 'अद्यतित',
    refreshQueue: 'कतार रिफ्रेश करें',
    activeTokensNotice: 'आपके पास {count} सक्रिय टोकन हैं:',
    weighedStatus: 'तौल पूर्ण',
    inYardStatus: 'यार्ड में',
    bookedStatus: 'बुक किया गया',

    // Radar Cards - Scenario 1: Completed
    weighbridgeScale1: 'इलेक्ट्रॉनिक धर्मकांटा #1',
    weighedDone: 'तौल संपन्न',
    quintals: 'क्विंटल',
    kg: 'किग्रा',
    produceWeighedVerified: 'उपज तौली एवं सत्यापित की गई',
    qualityGrade: 'गुणवत्ता ग्रेड',
    officialMsp: 'सरकारी एमएसपी',
    totalMspPayout: 'कुल एमएसपी देय राशि',
    dbtDisbursed: 'डीबीटी अंतरित',
    dbtQueued: 'डीबीटी प्रक्रियाधीन',
    dbtPaidDesc: 'आधार डीबीटी द्वारा भुगतान सीधे आपके बैंक खाते में अंतरित कर दिया गया है।',
    dbtQueuedDesc: 'भुगतान प्रक्रिया आरंभ हो गई है। सरकारी खजाने से 24-48 घंटों में राशि जमा हो जाएगी।',

    // Radar Cards - Scenario 2: In Yard
    nowServingScale1: 'धर्मकांटा #1 पर वर्तमान तौल',
    scaleServingBadge: 'धर्मकांटा तौल',
    scaleOpen: 'कांटा रिक्त है',
    scaleTractorPositioned: 'ट्रैक्टर वर्तमान में इलेक्ट्रॉनिक धर्मकांटे पर स्थित है',
    scaleOpenReady: 'कांटा रिक्त है और अगले वाहन के लिए तैयार है',
    inYardPosition: 'यार्ड में क्रम',
    yourTurnNow: 'अब आपकी बारी है!',
    queuePos: 'कतार क्रम #{pos}',
    checkedInAtGate: 'गेट पर प्रवेश सत्यापित',
    driveScaleNow: 'कृपया अपना ट्रैक्टर तुरंत धर्मकांटा #1 पर ले जाएं!',
    tractorsAheadYard: 'यार्ड कतार में आपके आगे {count} ट्रैक्टर हैं',
    gateVerifiedSync: 'गेट प्रवेश सत्यापित • धर्मकांटा प्रेषण के साथ समन्वय जारी...',

    // Radar Cards - Scenario 3: Pre-Arrival
    mandiScaleServing: 'मंडी धर्मकांटा #1 वर्तमान स्थिति',
    scaleOpenHome: 'कांटा रिक्त है',
    processingNow: 'तौल जारी',
    tractorsLinedUpYard: 'मंडी यार्ड में वर्तमान में {count} ट्रैक्टर कतार में हैं।',
    yourAdvanceBooking: 'आपकी अग्रिम बुकिंग',
    nextInTurn: 'अगली बारी आपकी है',
    tokensAheadPreArrival: 'आपसे आगे {count} टोकन हैं',
    estimatedScaleTurn: 'अनुमानित तौल समय ~{time} ({hours}घंटे {mins}मिनट)',
    tomorrowLabel: 'कल',
    scheduledSlotConfirmed: 'निर्धारित स्लॉट की पुष्टि हुई',
    scheduledForTomorrow: 'कल के लिए निर्धारित',
    scheduledForDate: '{date} के लिए निर्धारित',
    gateOpensTomorrowDesc: 'गेट सुरक्षा चेक-इन कल सुबह 9:00 बजे खुलेगा।',
    futureBookingNoticeTitle: '{date} को {time} के लिए स्लॉट की पुष्टि हुई',
    futureBookingNoticeBody: 'कृपया अपने भरे हुए वाहन और भूमि दस्तावेजों के साथ {date} को {center} पहुंचें। लाइव कतार रडार कल सुबह स्वचालित रूप से सक्रिय हो जाएगा।',
    step2ArriveTomorrow: '{date} को {time} पर पहुंचें',
    gateCheckInPending: 'गेट चेक-इन लंबित',
    turnNumberLabel: 'बारी #{num}',
    estimatedScaleTurnTime: 'अनुमानित तौल समय',
    procurementHistory: 'तौल एवं खरीद इतिहास',
    viewWeighedTokens: 'तौल पर्चियां',
    weighedTokensModalTitle: 'तौल पर्चियां एवं भुगतान स्थिति',
    weighedTokensModalSubtitle: 'आधिकारिक धर्मकांटा तौल रिकॉर्ड और प्रत्यक्ष लाभ अंतरण (DBT) भुगतान स्थिति',
    noWeighedTokensYet: 'अभी तक कोई तौल पर्ची नहीं है',
    noWeighedTokensDesc: 'मंडी धर्मकांटा #1 पर आपकी फसल तौले जाने के बाद, आपकी सत्यापित तौल पर्ची और डीबीटी भुगतान रिकॉर्ड यहां दिखाई देगा।',
    weighedOnDate: 'तौल दिनांक',
    scheduledGateArrival: 'मंडी गेट आगमन समय',
    futureStaggeredNotice: 'कृपया सुरक्षा चेक-इन के लिए लगभग ~{arrivalTime} तक मंडी गेट पहुंचें। धर्मकांटा पर आपकी अनुमानित तौल बारी ~{turnTime} (बारी #{turn}) है।',
    history: 'इतिहास',
    closeModal: 'बंद करें',

    // Notices
    lunchBreakTitle: 'मंडी भोजन अवकाश जारी (दोपहर 1:00 से 2:00 बजे)',
    lunchBreakDesc: 'कर्मचारियों के भोजन अवकाश के कारण धर्मकांटा कार्य स्थगित है। तौल कार्य ठीक 2:00 बजे पुनः प्रारंभ होगा।',
    resumesAtTwoPm: 'दोपहर 2:00 बजे पुनः प्रारंभ',
    gateClosedTitle: 'आज के लिए मंडी गेट प्रवेश बंद (शाम 5:00 बजे)',
    gateClosedInYardDesc: 'आपका ट्रैक्टर यार्ड के अंदर है। सभी चेक-इन वाहनों की तौल पूर्ण की जाएगी।',
    gateClosedHomeDesc: 'आज के लिए गेट प्रवेश बंद हो चुका है। शेष अग्रिम टोकन समाप्त हो चुके हैं। कृपया कल के लिए नया स्लॉट बुक करें।',
    gateClosedBadge: 'गेट बंद (शाम 5:00 बजे)',

    // Advisories
    congratsWeighedTitle: 'टोकन {token} की तौल संपन्न!',
    congratsWeighedBody: 'आपकी {crop} की खेप तौली एवं स्वीकार कर ली गई है। कुल ₹{amount} की एमएसपी राशि आपके बैंक खाते{bankSuffix} में डीबीटी के लिए दर्ज कर दी गई है।',
    bankAccountEnding: ' (अंतिम 4 अंक ••••{last4})',
    yardTurnNowTitle: 'टोकन {token} के लिए आपकी बारी आ गई है!',
    yardTurnNowBody: 'कृपया अपना ट्रैक्टर तुरंत धर्मकांटा #1 पर ले जाएं। अधिकारी तौल के लिए तैयार हैं।',
    yardGetReadyTitle: 'टोकन {token} के लिए तैयार हो जाएं!',
    yardGetReadyBody: 'आपके आगे केवल {count} ट्रैक्टर शेष हैं। कृपया अपना ट्रैक्टर चालू करें और तौल रैंप के निकट रहें।',
    yardRestShedTitle: 'किसान विश्राम गृह में विश्राम करें!',
    yardRestShedBody: 'यार्ड में आपके आगे {count} ट्रैक्टर हैं। जब 5 ट्रैक्टर बचेंगे, हम आपको सूचित करेंगे।',
    preArrivalUrgentTitle: 'टोकन {token} की बारी निकट है! कृपया गेट की ओर प्रस्थान करें',
    preArrivalUrgentBody: 'आपके आगे केवल {count} टोकन शेष हैं। चेक-इन करने हेतु तुरंत {center} के गेट #1 पर पहुंचें।',
    preArrivalRelaxTitle: 'घर पर आराम करें: आपकी अनुमानित बारी ~{time} पर है',
    preArrivalRelaxBody: 'कांटे पर टोकन {servingToken} का कार्य चल रहा है और आपसे आगे {ahead} टोकन हैं। कृपया अपनी बारी से 30 मिनट पूर्व (~{gateTime} तक) मंडी गेट पर पहुंचे।',
    earlierSlots: 'पूर्व टोकन',
    suggestedGateArrival: 'गेट पर पहुंचने का समय',
    immediately: 'तुरंत',

    // Traffic & Velocity
    yardTrafficTitle: 'मंडी यार्ड यातायात ({center})',
    fastFlow: 'सामान्य प्रवाह',
    yardTrafficDesc: 'यार्ड में {yardCount} ट्रैक्टर • आज {bookedCount} अग्रिम टोकन निर्धारित • औसत तौल समय: ~{avgMin} मिनट',
    yardWaitTimeLabel: 'यार्ड में अनुमानित प्रतीक्षा समय',
    estimatedTimeToTurnLabel: 'बारी आने का अनुमानित समय',
    zeroMinsProcured: '0 मिनट (तौल संपन्न)',
    zeroMinsAtScale: '0 मिनट (कांटे पर)',
    approxMinutes: '~{mins} मिनट',
    approxMinsWithTime: '~{mins} मिनट (~{time})',

    // 5-Step Journey Stepper
    procurementLifecycle: 'टोकन {token} की खरीद एवं भुगतान प्रगति',
    step1Title: 'स्लॉट बुक हुआ',
    step1Subtitle: 'पुष्टि हो गई',
    step2Title: 'गेट चेक-इन',
    step2EntryDone: 'प्रवेश संपन्न',
    step2CheckedIn: 'मंडी में उपस्थित',
    step2ReachGateNow: 'तुरंत गेट पहुंचें!',
    step2ArriveBy: '~{time} तक पहुंचें',
    step3Title: 'धर्मकांटा तौल',
    step3WeighingDone: 'तौल संपन्न',
    step3NowAtScale1: 'कांटा #1 पर उपस्थित',
    step3QueueNum: 'कतार क्रम #{pos}',
    step3InLine: 'कतार में',
    step4Title: 'उपज तौल पूर्ण',
    step4JFormIssued: 'जे-फार्म पर्ची जारी',
    step4AwaitingScale: 'तौल प्रतीक्षित',
    step5Title: 'डीबीटी बैंक भुगतान',
    step5Credited: 'बैंक खाते में अंतरित',
    step5InTransit: 'डीबीटी प्रक्रियाधीन',
    step5DirectDeposit: 'सीधा बैंक अंतरण',
    stepNum: 'चरण {num}',

    // Slot Booking
    smartSlotAllocation: 'स्मार्ट स्लॉट आवंटन',
    bookMandiArrivalSlot: 'मंडी आगमन स्लॉट बुक करें',
    slotBookingSubtitle: 'कतारों में प्रतीक्षा से बचने और डिजिटल टोकन प्राप्त करने हेतु आगमन समय आरक्षित करें',
    slotConfirmed: 'स्लॉट की पुष्टि हुई!',
    yourToken: 'आपका टोकन:',
    smsSimulatedHint: 'एसएमएस पुष्टि भेजी जा चुकी है। आगमन पर मंडी काउंटर पर यह टोकन दिखाएं।',
    bookAnotherSlot: 'अन्य स्लॉट बुक करें',
    mandiCenterLabel: 'मंडी खरीद केंद्र',
    loadingCenters: 'मंडी केंद्र लोड हो रहे हैं...',
    noCentersConfigured: 'सिस्टम में कोई केंद्र उपलब्ध नहीं है।',
    produceCropLabel: 'उपज फसल',
    arrivalDateLabel: 'आगमन तिथि',
    availableSlotsForCrop: '{crop} हेतु उपलब्ध आगमन स्लॉट',
    slotsAvailableCount: '{count} स्लॉट उपलब्ध',
    slotSingular: 'स्लॉट',
    slotPlural: 'स्लॉट',
    intakeCapacityFullTitle: 'आज के लिए मंडी क्षमता पूर्ण हो चुकी है',
    intakeCapacityFullDesc: 'आज की कतार शाम 5:00 बजे गेट बंदी से आगे जा चुकी है। आज के लिए और बुकिंग संभव नहीं है।',
    switchToTomorrow: 'कल के लिए स्लॉट देखें',
    checkingSlotAvailability: 'वास्तविक समय में स्लॉट उपलब्धता जांची जा रही है...',
    noOpenSlotsFound: 'इस तिथि एवं फसल के लिए कोई रिक्त स्लॉट नहीं मिला',
    noOpenSlotsDesc: 'मंडी प्रशासन ने इस संयोजन हेतु खरीद समय निर्धारित नहीं किया है। कृपया अन्य तिथि अथवा फसल चुनें।',
    intakeClosedCutoff: 'प्रवेश बंद (शाम 5 बजे कटऑफ)',
    slotFullBadge: 'पूर्ण',
    seatsLeftBadge: '{count} स्थान शेष',
    capacityBookedText: 'क्षमता: {booked} / {capacity} किसान बुक',
    reservingSeat: 'स्थान आरक्षित किया जा रहा है...',
    intakeFullBtn: 'प्रवेश पूर्ण (कटऑफ शाम 5:00 बजे)',
    slotFullBtn: 'स्लॉट पूर्ण',
    bookThisSlotBtn: 'यह स्लॉट बुक करें',

    // Farmer History
    myTokensPassbook: 'मेरे टोकन एवं मंडी पासबुक',
    historySubtitle: 'सक्रिय आगमन पास, काउंटर प्रगति और डीबीटी भुगतान स्थिति देखें',
    refreshHistory: 'इतिहास रिफ्रेश करें',
    loadingPassbook: 'डिजिटल पासबुक लोड की जा रही है...',
    noHistoryYet: 'अभी तक कोई बुकिंग इतिहास नहीं है',
    noHistoryDesc: 'आपने अभी तक कोई मंडी स्लॉट बुक नहीं किया है। अपना पहला आगमन स्लॉट बुक करने के लिए ऊपर दिए गए अनुभाग का उपयोग करें।',
    statusBooked: 'स्लॉट बुक हुआ',
    statusCheckedIn: 'मंडी कतार में',
    statusCompleted: 'तौल संपन्न',
    statusCancelled: 'रद्द किया गया',
    paymentAwaitingWeighing: 'तौल की प्रतीक्षा',
    paymentPaidViaDbt: 'डीबीटी भुगतान सफल',
    paymentProcessing: 'प्रक्रियाधीन',
    paymentPending: 'भुगतान लंबित',
    tokenLabel: 'टोकन',
    atTime: 'समय',
    cropLabel: 'फसल',
    cancelSlot: 'स्लॉट रद्द करें',
    cancelling: 'रद्द किया जा रहा है...',
    confirmCancelBooking: 'क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं? यह स्लॉट अन्य किसानों के लिए उपलब्ध हो जाएगा।',
  },

  pa: {
    // Navbar
    kisanMandi: 'ਕਿਸਾਨ ਮੰਡੀ',
    eProcurement: 'ਈ-ਉਪਾਰਜਨ',
    deptSubtitle: 'ਖਪਤਕਾਰ ਮਾਮਲੇ ਵਿਭਾਗ • ਸਮਾਰਟ ਖਰੀਦ ਪ੍ਰਣਾਲੀ',
    registeredFarmer: 'ਰਜਿਸਟਰਡ ਕਿਸਾਨ',
    farmer: 'ਕਿਸਾਨ',
    signOut: 'ਲਾਗ ਆਊਟ',
    selectLanguage: 'ਭਾਸ਼ਾ',

    // Farmer Login & Registration
    backToHome: 'ਮੁੱਖ ਪੰਨੇ ਤੇ ਵਾਪਸ',
    kisanPortal: 'ਕਿਸਾਨ ਪੋਰਟਲ',
    farmerSignInTitle: 'ਕਿਸਾਨ ਲੌਗਇਨ',
    farmerSignInSubtitle: 'ਆਪਣੇ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਰਾਹੀਂ ਓਟੀਪੀ ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    farmerRegisterTitle: 'ਨਵਾਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    farmerRegisterSubtitle: 'ਮੰਡੀ ਸਲਾਟ ਬੁੱਕ ਕਰਨ ਅਤੇ ਸਿੱਧਾ ਐਮਐਸਪੀ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਇੱਕ ਵਾਰ ਰਜਿਸਟਰ ਕਰੋ',
    tabSignIn: 'ਕਿਸਾਨ ਲੌਗਇਨ (ਓਟੀਪੀ)',
    tabRegister: 'ਨਵਾਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    mobileNumberLabel: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    mobileNumberPlaceholder: 'ਉਦਾ. 9876543210',
    mobileNumberHelp: 'ਆਪਣੇ ਪੀਐਮ-ਕਿਸਾਨ ਜਾਂ ਮੰਡੀ ਖਾਤੇ ਨਾਲ ਜੁੜਿਆ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
    sendLoginOtp: 'ਲੌਗਇਨ ਓਟੀਪੀ ਭੇਜੋ',
    sendingOtp: 'ਓਟੀਪੀ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    enterOtpLabel: '6 ਅੰਕਾਂ ਦਾ ਓਟੀਪੀ ਦਰਜ ਕਰੋ',
    changeNumber: 'ਨੰਬਰ ਬਦਲੋ',
    verifyAndSignIn: 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਲੌਗਇਨ ਕਰੋ',
    verifying: 'ਪੁਸ਼ਟੀ ਜਾਰੀ ਹੈ...',
    resendOtp: 'ਓਟੀਪੀ ਨਹੀਂ ਮਿਲਿਆ? ਦੁਬਾਰਾ ਭੇਜੋ',
    simulatedSmsCode: 'ਸਿਮੂਲੇਟਿਡ ਐਸਐਮਐਸ ਕੋਡ',
    autoFilled: 'ਆਟੋ-ਫਿਲਡ',
    fullNameLabel: 'ਪੂਰਾ ਨਾਮ',
    fullNamePlaceholder: 'ਉਦਾ. ਹਰਪ੍ਰੀਤ ਸਿੰਘ',
    villageDistrictLabel: 'ਪਿੰਡ / ਜ਼ਿਲ੍ਹਾ',
    villageDistrictPlaceholder: 'ਉਦਾ. ਸਮਾਣਾ, ਪਟਿਆਲਾ',
    landRecordLabel: 'ਖਸਰਾ / ਜ਼ਮੀਨ ਦਾ ਰਿਕਾਰਡ',
    landRecordPlaceholder: 'ਉਦਾ. KH-45892/2024',
    bankAccountLabel: 'ਡੀਬੀਟੀ ਬੈਂਕ ਖਾਤਾ ਨੰਬਰ',
    bankAccountPlaceholder: 'ਉਦਾ. 123456789012',
    registerAndContinue: 'ਰਜਿਸਟਰ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ',
    registering: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਜਾਰੀ ਹੈ...',
    loginGovFooter: 'ਖਪਤਕਾਰ ਮਾਮਲੇ, ਖੁਰਾਕ ਅਤੇ ਜਨਤਕ ਵੰਡ ਮੰਤਰਾਲਾ • ਸਿੱਧਾ ਕਿਸਾਨ ਐਮਐਸਪੀ ਪੋਰਟਲ',
    validPhoneError: 'ਕਿਰਪਾ ਕਰਕੇ 10 ਅੰਕਾਂ ਦਾ ਵੈਧ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
    farmerNotFoundError: 'ਇਸ ਨੰਬਰ ਤੇ ਕੋਈ ਕਿਸਾਨ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਹੇਠਾਂ "ਨਵਾਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ" ਤੇ ਕਲਿੱਕ ਕਰੋ।',
    otpSentSuccess: '+91 {phone} ਤੇ ਓਟੀਪੀ ਭੇਜਿਆ ਗਿਆ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਦਰਜ ਕਰੋ।',
    validOtpError: 'ਕਿਰਪਾ ਕਰਕੇ 6 ਅੰਕਾਂ ਦਾ ਓਟੀਪੀ ਕੋਡ ਦਰਜ ਕਰੋ।',
    signInSuccess: 'ਸਫਲਤਾਪੂਰਵਕ ਲੌਗਇਨ ਹੋ ਗਿਆ! ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ ਤੇ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    registerRequiredFields: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਅਤੇ ਮੋਬਾਈਲ ਨੰਬਰ ਦੋਵੇਂ ਦਰਜ ਕਰੋ।',
    registeredSuccess: 'ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ ਰਹੀ! ਡੈਸ਼ਬੋਰਡ ਤੇ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    alreadyRegisteredPhone: 'ਇਹ ਮੋਬਾਈਲ ਨੰਬਰ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਉੱਪਰ "ਕਿਸਾਨ ਲੌਗਇਨ" ਚੁਣੋ।',

    // Farmer Home
    kisanDashboard: 'ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ',
    welcomeGreeting: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
    homeSubtitle: 'ਆਪਣੀ ਮੰਡੀ ਫੇਰੀ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ, ਲੰਬੀਆਂ ਕਤਾਰਾਂ ਤੋਂ ਬਚੋ ਅਤੇ ਸਿੱਧਾ ਆਪਣੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਐਮਐਸਪੀ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਕਰੋ।',
    landRecordKhasra: 'ਖਸਰਾ / ਜ਼ਮੀਨ ਦਾ ਰਿਕਾਰਡ',
    verifiedLand: 'ਪ੍ਰਮਾਣਿਤ ਜ਼ਮੀਨ',
    dbtBankLinked: 'ਡੀਬੀਟੀ ਬੈਂਕ ਖਾਤਾ ਲਿੰਕ',
    active: 'ਸਰਗਰਮ',
    smsSimulationTitle: 'ਸਿਮੂਲੇਟਿਡ ਐਸਐਮਐਸ ਚੇਤਾਵਨੀ (DoCA-GOV)',
    smsDeliveredTo: '{phone} ਤੇ ਭੇਜਿਆ ਗਿਆ • ਡਿਜੀਟਲ ਕਤਾਰ ਟੋਕਨ',
    footerHackathon: 'ਸਮਾਰਟ ਇੰਡੀਆ ਹੈਕਾਥਨ 2024 • ਖਪਤਕਾਰ ਮਾਮਲੇ, ਖੁਰਾਕ ਅਤੇ ਜਨਤਕ ਵੰਡ ਮੰਤਰਾਲਾ',
    footerPlatform: 'ਸਮਾਰਟ ਆਟੋਮੇਸ਼ਨ ਅਤੇ ਰੀਅਲ-ਟਾਈਮ ਖਰੀਦ ਪਲੇਟਫਾਰਮ',

    // Live Queue Tracker
    radarCompleted: 'ਤੋਲ ਮੁਕੰਮਲ ਅਤੇ ਪ੍ਰਵਾਨਿਤ',
    radarInYard: 'ਲਾਈਵ ਮੰਡੀ ਯਾਰਡ ਰਾਡਾਰ',
    radarPreArrival: 'ਪੇਸ਼ਗੀ ਟੋਕਨ ਰਾਡਾਰ',
    mandiCenterDefault: 'ਮੰਡੀ ਖਰੀਦ ਕੇਂਦਰ',
    completedTokenPrefix: 'ਮੁਕੰਮਲ ਟੋਕਨ: ',
    inYardTokenPrefix: 'ਯਾਰਡ ਵਿੱਚ ਟੋਕਨ: ',
    advanceTokenPrefix: 'ਪੇਸ਼ਗੀ ਟੋਕਨ: ',
    updated: 'ਅੱਪਡੇਟ ਕੀਤਾ',
    refreshQueue: 'ਕਤਾਰ ਤਾਜ਼ਾ ਕਰੋ',
    activeTokensNotice: 'ਤੁਹਾਡੇ ਕੋਲ {count} ਸਰਗਰਮ ਟੋਕਨ ਹਨ:',
    weighedStatus: 'ਤੋਲਿਆ ਗਿਆ',
    inYardStatus: 'ਯਾਰਡ ਵਿੱਚ',
    bookedStatus: 'ਬੁੱਕ ਕੀਤਾ',

    // Radar Cards - Scenario 1: Completed
    weighbridgeScale1: 'ਇਲੈਕਟ੍ਰਾਨਿਕ ਧਰਮਕੰਡਾ #1',
    weighedDone: 'ਤੋਲ ਮੁਕੰਮਲ',
    quintals: 'ਕੁਇੰਟਲ',
    kg: 'ਕਿਲੋਗ੍ਰਾਮ',
    produceWeighedVerified: 'ਫਸਲ ਤੋਲੀ ਅਤੇ ਪ੍ਰਮਾਣਿਤ ਕੀਤੀ ਗਈ',
    qualityGrade: 'ਕੁਆਲਿਟੀ ਗ੍ਰੇਡ',
    officialMsp: 'ਸਰਕਾਰੀ ਐਮਐਸਪੀ',
    totalMspPayout: 'ਕੁੱਲ ਐਮਐਸਪੀ ਭੁਗਤਾਨ',
    dbtDisbursed: 'ਡੀਬੀਟੀ ਭੇਜਿਆ ਗਿਆ',
    dbtQueued: 'ਡੀਬੀਟੀ ਕਤਾਰ ਵਿੱਚ',
    dbtPaidDesc: 'ਆਧਾਰ ਡੀਬੀਟੀ ਰਾਹੀਂ ਭੁਗਤਾਨ ਸਿੱਧਾ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਜਮ੍ਹਾਂ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।',
    dbtQueuedDesc: 'ਭੁਗਤਾਨ ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਹੋ ਚੁੱਕੀ ਹੈ। ਸਰਕਾਰੀ ਖ਼ਜ਼ਾਨੇ ਵੱਲੋਂ 24-48 ਘੰਟਿਆਂ ਵਿੱਚ ਰਕਮ ਜਮ੍ਹਾਂ ਹੋ ਜਾਵੇਗੀ।',

    // Radar Cards - Scenario 2: In Yard
    nowServingScale1: 'ਧਰਮਕੰਡਾ #1 ਤੇ ਮੌਜੂਦਾ ਤੋਲ',
    scaleServingBadge: 'ਧਰਮਕੰਡਾ ਤੋਲ',
    scaleOpen: 'ਕੰਡਾ ਖਾਲੀ ਹੈ',
    scaleTractorPositioned: 'ਟਰੈਕਟਰ ਇਸ ਵੇਲੇ ਇਲੈਕਟ੍ਰਾਨਿਕ ਧਰਮਕੰਡੇ ਤੇ ਮੌਜੂਦ ਹੈ',
    scaleOpenReady: 'ਕੰਡਾ ਖਾਲੀ ਹੈ ਅਤੇ ਅਗਲੇ ਵਾਹਨ ਲਈ ਤਿਆਰ ਹੈ',
    inYardPosition: 'ਯਾਰਡ ਵਿੱਚ ਸਥਿਤੀ',
    yourTurnNow: 'ਹੁਣ ਤੁਹਾਡੀ ਵਾਰੀ ਹੈ!',
    queuePos: 'ਕਤਾਰ ਨੰਬਰ #{pos}',
    checkedInAtGate: 'ਗੇਟ ਤੇ ਐਂਟਰੀ ਦਰਜ',
    driveScaleNow: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਟਰੈਕਟਰ ਤੁਰੰਤ ਧਰਮਕੰਡਾ #1 ਤੇ ਲੈ ਜਾਓ!',
    tractorsAheadYard: 'ਯਾਰਡ ਕਤਾਰ ਵਿੱਚ ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ {count} ਟਰੈਕਟਰ ਹਨ',
    gateVerifiedSync: 'ਗੇਟ ਐਂਟਰੀ ਤਸਦੀਕ ਹੋਈ • ਧਰਮਕੰਡੇ ਨਾਲ ਤਾਲਮੇਲ ਜਾਰੀ...',

    // Radar Cards - Scenario 3: Pre-Arrival
    mandiScaleServing: 'ਮੰਡੀ ਧਰਮਕੰਡਾ #1 ਮੌਜੂਦਾ ਸਥਿਤੀ',
    scaleOpenHome: 'ਕੰਡਾ ਖਾਲੀ ਹੈ',
    processingNow: 'ਤੋਲ ਜਾਰੀ',
    tractorsLinedUpYard: 'ਮੰਡੀ ਯਾਰਡ ਵਿੱਚ ਇਸ ਵੇਲੇ {count} ਟਰੈਕਟਰ ਕਤਾਰ ਵਿੱਚ ਹਨ।',
    yourAdvanceBooking: 'ਤੁਹਾਡੀ ਪੇਸ਼ਗੀ ਬੁਕਿੰਗ',
    nextInTurn: 'ਅਗਲੀ ਵਾਰੀ ਤੁਹਾਡੀ ਹੈ',
    tokensAheadPreArrival: 'ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ {count} ਟੋਕਨ ਹਨ',
    estimatedScaleTurn: 'ਅੰਦਾਜ਼ਨ ਤੋਲ ਦਾ ਸਮਾਂ ~{time} ({hours}ਘੰਟੇ {mins}ਮਿੰਟ)',
    tomorrowLabel: 'ਕੱਲ੍ਹ',
    scheduledSlotConfirmed: 'ਨਿਰਧਾਰਤ ਸਲਾਟ ਦੀ ਪੁਸ਼ਟੀ ਹੋਈ',
    scheduledForTomorrow: 'ਕੱਲ੍ਹ ਲਈ ਨਿਰਧਾਰਤ',
    scheduledForDate: '{date} ਲਈ ਨਿਰਧਾਰਤ',
    gateOpensTomorrowDesc: 'ਗੇਟ ਸੁਰੱਖਿਆ ਚੈੱਕ-ਇਨ ਕੱਲ੍ਹ ਸਵੇਰੇ 9:00 ਵਜੇ ਸ਼ੁਰੂ ਹੋਵੇਗਾ।',
    futureBookingNoticeTitle: '{date} ਨੂੰ {time} ਲਈ ਸਲਾਟ ਦੀ ਪੁਸ਼ਟੀ ਹੋਈ',
    futureBookingNoticeBody: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਭਰੇ ਹੋਏ ਵਾਹਨ ਅਤੇ ਜ਼ਮੀਨੀ ਦਸਤਾਵੇਜ਼ਾਂ ਸਮੇਤ {date} ਨੂੰ {center} ਪਹੁੰਚੋ। ਲਾਈਵ ਕਤਾਰ ਰਾਡਾਰ ਕੱਲ੍ਹ ਸਵੇਰੇ ਆਪਣੇ ਆਪ ਚਾਲੂ ਹੋ ਜਾਵੇਗਾ।',
    step2ArriveTomorrow: '{date} ਨੂੰ {time} ਤੇ ਪਹੁੰਚੋ',
    gateCheckInPending: 'ਗੇਟ ਚੈੱਕ-ਇਨ ਬਕਾਇਆ',
    turnNumberLabel: 'ਵਾਰੀ #{num}',
    estimatedScaleTurnTime: 'ਅੰਦਾਜ਼ਨ ਤੋਲ ਸਮਾਂ',
    procurementHistory: 'ਤੋਲ ਅਤੇ ਖਰੀਦ ਇਤਿਹਾਸ',
    viewWeighedTokens: 'ਤੋਲ ਪਰਚੀਆਂ',
    weighedTokensModalTitle: 'ਤੋਲ ਪਰਚੀਆਂ ਅਤੇ ਭੁਗਤਾਨ ਸਥਿਤੀ',
    weighedTokensModalSubtitle: 'ਅਧਿਕਾਰਤ ਧਰਮਕੰਡਾ ਤੋਲ ਰਿਕਾਰਡ ਅਤੇ ਡੀਬੀਟੀ ਭੁਗਤਾਨ ਸਥਿਤੀ',
    noWeighedTokensYet: 'ਅਜੇ ਕੋਈ ਤੋਲ ਪਰਚੀ ਨਹੀਂ ਹੈ',
    noWeighedTokensDesc: 'ਮੰਡੀ ਧਰਮਕੰਡਾ #1 ਤੇ ਤੁਹਾਡੀ ਫਸਲ ਤੁਲਣ ਤੋਂ ਬਾਅਦ, ਤੁਹਾਡੀ ਤੋਲ ਪਰਚੀ ਅਤੇ ਡੀਬੀਟੀ ਭੁਗਤਾਨ ਰਿਕਾਰਡ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗਾ।',
    weighedOnDate: 'ਤੋਲ ਮਿਤੀ',
    scheduledGateArrival: 'ਮੰਡੀ ਗੇਟ ਪਹੁੰਚਣ ਦਾ ਸਮਾਂ',
    futureStaggeredNotice: 'ਕਿਰਪਾ ਕਰਕੇ ਸੁਰੱਖਿਆ ਚੈੱਕ-ਇਨ ਲਈ ਲਗਭਗ ~{arrivalTime} ਤੱਕ ਮੰਡੀ ਗੇਟ ਪਹੁੰਚੋ। ਧਰਮਕੰਡੇ ਤੇ ਤੁਹਾਡੀ ਅੰਦਾਜ਼ਨ ਤੋਲ ਵਾਰੀ ~{turnTime} (ਵਾਰੀ #{turn}) ਹੈ।',
    history: 'ਇਤਿਹਾਸ',
    closeModal: 'ਬੰਦ ਕਰੋ',

    // Notices
    lunchBreakTitle: 'ਮੰਡੀ ਦੁਪਹਿਰ ਦਾ ਖਾਣਾ ਬਰੇਕ (ਦੁਪਹਿਰ 1:00 ਤੋਂ 2:00 ਵਜੇ)',
    lunchBreakDesc: 'ਸਟਾਫ਼ ਦੇ ਦੁਪਹਿਰ ਦੇ ਖਾਣੇ ਕਾਰਨ ਧਰਮਕੰਡਾ ਬੰਦ ਹੈ। ਤੋਲ ਦਾ ਕੰਮ ਠੀਕ 2:00 ਵਜੇ ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਹੋਵੇਗਾ।',
    resumesAtTwoPm: 'ਦੁਪਹਿਰ 2:00 ਵਜੇ ਸ਼ੁਰੂ ਹੋਵੇਗਾ',
    gateClosedTitle: 'ਅੱਜ ਲਈ ਮੰਡੀ ਗੇਟ ਐਂਟਰੀ ਬੰਦ (ਸ਼ਾਮ 5:00 ਵਜੇ)',
    gateClosedInYardDesc: 'ਤੁਹਾਡਾ ਟਰੈਕਟਰ ਯਾਰਡ ਦੇ ਅੰਦਰ ਹੈ। ਸਾਰੇ ਚੈੱਕ-ਇਨ ਕੀਤੇ ਵਾਹਨਾਂ ਦਾ ਤੋਲ ਮੁਕੰਮਲ ਕੀਤਾ ਜਾਵੇਗਾ।',
    gateClosedHomeDesc: 'ਅੱਜ ਲਈ ਗੇਟ ਐਂਟਰੀ ਬੰਦ ਹੋ ਚੁੱਕੀ ਹੈ। ਬਾਕੀ ਪੇਸ਼ਗੀ ਟੋਕਨ ਰੱਦ ਹੋ ਗਏ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਕੱਲ੍ਹ ਲਈ ਨਵਾਂ ਸਲਾਟ ਬੁੱਕ ਕਰੋ।',
    gateClosedBadge: 'ਗੇਟ ਬੰਦ (ਸ਼ਾਮ 5:00 ਵਜੇ)',

    // Advisories
    congratsWeighedTitle: 'ਟੋਕਨ {token} ਦਾ ਤੋਲ ਮੁਕੰਮਲ!',
    congratsWeighedBody: 'ਤੁਹਾਡੀ {crop} ਦੀ ਖੇਪ ਤੋਲੀ ਅਤੇ ਪ੍ਰਵਾਨ ਕਰ ਲਈ ਗਈ ਹੈ। ਕੁੱਲ ₹{amount} ਦੀ ਐਮਐਸਪੀ ਰਕਮ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ{bankSuffix} ਵਿੱਚ ਡੀਬੀਟੀ ਲਈ ਦਰਜ ਕਰ ਲਈ ਗਈ ਹੈ।',
    bankAccountEnding: ' (ਆਖਰੀ 4 ਅੰਕ ••••{last4})',
    yardTurnNowTitle: 'ਟੋਕਨ {token} ਲਈ ਤੁਹਾਡੀ ਵਾਰੀ ਆ ਗਈ ਹੈ!',
    yardTurnNowBody: 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਟਰੈਕਟਰ ਤੁਰੰਤ ਧਰਮਕੰਡਾ #1 ਤੇ ਲੈ ਜਾਓ। ਅਧਿਕਾਰੀ ਤੋਲ ਲਈ ਤਿਆਰ ਹਨ।',
    yardGetReadyTitle: 'ਟੋਕਨ {token} ਲਈ ਤਿਆਰ ਹੋ ਜਾਓ!',
    yardGetReadyBody: 'ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਸਿਰਫ {count} ਟਰੈਕਟਰ ਬਾਕੀ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਟਰੈਕਟਰ ਚਾਲੂ ਕਰੋ ਅਤੇ ਧਰਮਕੰਡੇ ਨੇੜੇ ਰਹੋ।',
    yardRestShedTitle: 'ਕਿਸਾਨ ਆਰਾਮ ਘਰ ਵਿੱਚ ਆਰਾਮ ਕਰੋ!',
    yardRestShedBody: 'ਯਾਰਡ ਵਿੱਚ ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ {count} ਟਰੈਕਟਰ ਹਨ। ਜਦੋਂ 5 ਟਰੈਕਟਰ ਬਚਣਗੇ, ਅਸੀਂ ਤੁਹਾਨੂੰ ਸੂਚਿਤ ਕਰਾਂਗੇ।',
    preArrivalUrgentTitle: 'ਟੋਕਨ {token} ਦੀ ਵਾਰੀ ਨੇੜੇ ਹੈ! ਕਿਰਪਾ ਕਰਕੇ ਗੇਟ ਵੱਲ ਵਧੋ',
    preArrivalUrgentBody: 'ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ ਸਿਰਫ {count} ਟੋਕਨ ਬਾਕੀ ਹਨ। ਚੈੱਕ-ਇਨ ਕਰਨ ਲਈ ਤੁਰੰਤ {center} ਗੇਟ #1 ਤੇ ਪਹੁੰਚੋ।',
    preArrivalRelaxTitle: 'ਘਰ ਆਰਾਮ ਕਰੋ: ਤੁਹਾਡੀ ਅੰਦਾਜ਼ਨ ਵਾਰੀ ~{time} ਤੇ ਹੈ',
    preArrivalRelaxBody: 'ਕੰਡੇ ਤੇ ਟੋਕਨ {servingToken} ਦਾ ਕੰਮ ਚੱਲ ਰਿਹਾ ਹੈ ਅਤੇ ਤੁਹਾਡੇ ਤੋਂ ਅੱਗੇ {ahead} ਟੋਕਨ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਵਾਰੀ ਤੋਂ 30 ਮਿੰਟ ਪਹਿਲਾਂ (~{gateTime} ਤੱਕ) ਮੰਡੀ ਗੇਟ ਤੇ ਪਹੁੰਚੋ।',
    earlierSlots: 'ਪਹਿਲੇ ਟੋਕਨ',
    suggestedGateArrival: 'ਗੇਟ ਤੇ ਪਹੁੰਚਣ ਦਾ ਸੁਝਾਇਆ ਸਮਾਂ',
    immediately: 'ਤੁਰੰਤ',

    // Traffic & Velocity
    yardTrafficTitle: 'ਮੰਡੀ ਯਾਰਡ ਆਵਾਜਾਈ ({center})',
    fastFlow: 'ਤੇਜ਼ ਪ੍ਰਵਾਹ',
    yardTrafficDesc: 'ਯਾਰਡ ਵਿੱਚ {yardCount} ਟਰੈਕਟਰ • ਅੱਜ {bookedCount} ਪੇਸ਼ਗੀ ਟੋਕਨ • ਔਸਤ ਤੋਲ ਸਮਾਂ: ~{avgMin} ਮਿੰਟ',
    yardWaitTimeLabel: 'ਯਾਰਡ ਵਿੱਚ ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ',
    estimatedTimeToTurnLabel: 'ਵਾਰੀ ਆਉਣ ਦਾ ਅੰਦਾਜ਼ਨ ਸਮਾਂ',
    zeroMinsProcured: '0 ਮਿੰਟ (ਤੋਲ ਮੁਕੰਮਲ)',
    zeroMinsAtScale: '0 ਮਿੰਟ (ਕੰਡੇ ਤੇ)',
    approxMinutes: '~{mins} ਮਿੰਟ',
    approxMinsWithTime: '~{mins} ਮਿੰਟ (~{time})',

    // 5-Step Journey Stepper
    procurementLifecycle: 'ਟੋਕਨ {token} ਦੀ ਖਰੀਦ ਅਤੇ ਭੁਗਤਾਨ ਪ੍ਰਗਤੀ',
    step1Title: 'ਸਲਾਟ ਬੁੱਕ ਹੋਇਆ',
    step1Subtitle: 'ਪੁਸ਼ਟੀ ਹੋਈ',
    step2Title: 'ਗੇਟ ਚੈੱਕ-ਇਨ',
    step2EntryDone: 'ਐਂਟਰੀ ਮੁਕੰਮਲ',
    step2CheckedIn: 'ਮੰਡੀ ਵਿੱਚ ਹਾਜ਼ਰ',
    step2ReachGateNow: 'ਤੁਰੰਤ ਗੇਟ ਪਹੁੰਚੋ!',
    step2ArriveBy: '~{time} ਤੱਕ ਪਹੁੰਚੋ',
    step3Title: 'ਧਰਮਕੰਡਾ ਤੋਲ',
    step3WeighingDone: 'ਤੋਲ ਮੁਕੰਮਲ',
    step3NowAtScale1: 'ਕੰਡਾ #1 ਤੇ ਮੌਜੂਦ',
    step3QueueNum: 'ਕਤਾਰ ਨੰਬਰ #{pos}',
    step3InLine: 'ਕਤਾਰ ਵਿੱਚ',
    step4Title: 'ਫਸਲ ਤੋਲ ਮੁਕੰਮਲ',
    step4JFormIssued: 'ਜੇ-ਫਾਰਮ ਪਰਚੀ ਜਾਰੀ',
    step4AwaitingScale: 'ਤੋਲ ਦੀ ਉਡੀਕ',
    step5Title: 'ਡੀਬੀਟੀ ਬੈਂਕ ਭੁਗਤਾਨ',
    step5Credited: 'ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਜਮ੍ਹਾਂ',
    step5InTransit: 'ਡੀਬੀਟੀ ਪ੍ਰਕਿਰਿਆਧੀਨ',
    step5DirectDeposit: 'ਸਿੱਧਾ ਬੈਂਕ ਭੁਗਤਾਨ',
    stepNum: 'ਕਦਮ {num}',

    // Slot Booking
    smartSlotAllocation: 'ਸਮਾਰਟ ਸਲਾਟ ਵੰਡ',
    bookMandiArrivalSlot: 'ਮੰਡੀ ਆਮਦ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    slotBookingSubtitle: 'ਕਤਾਰਾਂ ਵਿੱਚ ਉਡੀਕ ਤੋਂ ਬਚਣ ਅਤੇ ਡਿਜੀਟਲ ਟੋਕਨ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਮਦ ਦਾ ਸਮਾਂ ਰਾਖਵਾਂ ਕਰੋ',
    slotConfirmed: 'ਸਲਾਟ ਦੀ ਪੁਸ਼ਟੀ ਹੋਈ!',
    yourToken: 'ਤੁਹਾਡਾ ਟੋਕਨ:',
    smsSimulatedHint: 'ਐਸਐਮਐਸ ਪੁਸ਼ਟੀ ਭੇਜ ਦਿੱਤੀ ਗਈ ਹੈ। ਮੰਡੀ ਕਾਊਂਟਰ ਤੇ ਇਹ ਟੋਕਨ ਦਿਖਾਓ।',
    bookAnotherSlot: 'ਹੋਰ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    mandiCenterLabel: 'ਮੰਡੀ ਖਰੀਦ ਕੇਂਦਰ',
    loadingCenters: 'ਮੰਡੀ ਕੇਂਦਰ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...',
    noCentersConfigured: 'ਸਿਸਟਮ ਵਿੱਚ ਕੋਈ ਕੇਂਦਰ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
    produceCropLabel: 'ਫਸਲ',
    arrivalDateLabel: 'ਆਮਦ ਦੀ ਮਿਤੀ',
    availableSlotsForCrop: '{crop} ਲਈ ਉਪਲਬਧ ਆਮਦ ਸਲਾਟ',
    slotsAvailableCount: '{count} ਸਲਾਟ ਉਪਲਬਧ',
    slotSingular: 'ਸਲਾਟ',
    slotPlural: 'ਸਲਾਟ',
    intakeCapacityFullTitle: 'ਅੱਜ ਲਈ ਮੰਡੀ ਦੀ ਸਮਰੱਥਾ ਪੂਰੀ ਹੋ ਚੁੱਕੀ ਹੈ',
    intakeCapacityFullDesc: 'ਅੱਜ ਦੀ ਕਤਾਰ ਸ਼ਾਮ 5:00 ਵਜੇ ਗੇਟ ਬੰਦ ਹੋਣ ਤੋਂ ਅੱਗੇ ਜਾ ਚੁੱਕੀ ਹੈ। ਅੱਜ ਲਈ ਹੋਰ ਬੁਕਿੰਗ ਸੰਭਵ ਨਹੀਂ ਹੈ।',
    switchToTomorrow: 'ਕੱਲ੍ਹ ਲਈ ਬੁੱਕ ਕਰੋ',
    checkingSlotAvailability: 'ਅਸਲ ਸਮੇਂ ਵਿੱਚ ਸਲਾਟ ਉਪਲਬਧਤਾ ਦੀ ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    noOpenSlotsFound: 'ਇਸ ਮਿਤੀ ਅਤੇ ਫਸਲ ਲਈ ਕੋਈ ਖਾਲੀ ਸਲਾਟ ਨਹੀਂ ਮਿਲਿਆ',
    noOpenSlotsDesc: 'ਮੰਡੀ ਪ੍ਰਸ਼ਾਸਨ ਨੇ ਇਸ ਫਸਲ ਲਈ ਖਰੀਦ ਸਮਾਂ ਨਿਰਧਾਰਤ ਨਹੀਂ ਕੀਤਾ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਹੋਰ ਮਿਤੀ ਜਾਂ ਫਸਲ ਚੁਣੋ।',
    intakeClosedCutoff: 'ਦਾਖਲਾ ਬੰਦ (ਸ਼ਾਮ 5 ਵਜੇ ਕੱਟ-ਆਫ)',
    slotFullBadge: 'ਪੂਰਾ ਭਰਿਆ',
    seatsLeftBadge: '{count} ਥਾਵਾਂ ਬਾਕੀ',
    capacityBookedText: 'ਸਮਰੱਥਾ: {booked} / {capacity} ਕਿਸਾਨ ਬੁੱਕ',
    reservingSeat: 'ਸਲਾਟ ਰਾਖਵਾਂ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    intakeFullBtn: 'ਸਮਰੱਥਾ ਪੂਰੀ (ਕੱਟ-ਆਫ ਸ਼ਾਮ 5:00 ਵਜੇ)',
    slotFullBtn: 'ਸਲਾਟ ਭਰਿਆ ਹੈ',
    bookThisSlotBtn: 'ਇਹ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',

    // Farmer History
    myTokensPassbook: 'ਮੇਰੇ ਟੋਕਨ ਅਤੇ ਮੰਡੀ ਪਾਸਬੁੱਕ',
    historySubtitle: 'ਸਰਗਰਮ ਪਾਸ, ਕਾਊਂਟਰ ਪ੍ਰਗਤੀ ਅਤੇ ਡੀਬੀਟੀ ਭੁਗਤਾਨ ਸਥਿਤੀ ਦੇਖੋ',
    refreshHistory: 'ਇਤਿਹਾਸ ਤਾਜ਼ਾ ਕਰੋ',
    loadingPassbook: 'ਡਿਜੀਟਲ ਪਾਸਬੁੱਕ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
    noHistoryYet: 'ਅਜੇ ਤੱਕ ਕੋਈ ਬੁਕਿੰਗ ਇਤਿਹਾਸ ਨਹੀਂ ਹੈ',
    noHistoryDesc: 'ਤੁਸੀਂ ਅਜੇ ਤੱਕ ਕੋਈ ਮੰਡੀ ਸਲਾਟ ਬੁੱਕ ਨਹੀਂ ਕੀਤਾ ਹੈ। ਆਪਣਾ ਪਹਿਲਾ ਸਲਾਟ ਬੁੱਕ ਕਰਨ ਲਈ ਉੱਪਰਲੇ ਭਾਗ ਦੀ ਵਰਤੋਂ ਕਰੋ।',
    statusBooked: 'ਸਲਾਟ ਬੁੱਕ ਹੋਇਆ',
    statusCheckedIn: 'ਮੰਡੀ ਕਤਾਰ ਵਿੱਚ',
    statusCompleted: 'ਤੋਲ ਮੁਕੰਮਲ',
    statusCancelled: 'ਰੱਦ ਕੀਤਾ ਗਿਆ',
    paymentAwaitingWeighing: 'ਤੋਲ ਦੀ ਉਡੀਕ',
    paymentPaidViaDbt: 'ਡੀਬੀਟੀ ਰਾਹੀਂ ਭੁਗਤਾਨ',
    paymentProcessing: 'ਜਾਰੀ ਹੈ',
    paymentPending: 'ਭੁਗਤਾਨ ਬਕਾਇਆ',
    tokenLabel: 'ਟੋਕਨ',
    atTime: 'ਸਮਾਂ',
    cropLabel: 'ਫਸਲ',
    cancelSlot: 'ਸਲਾਟ ਰੱਦ ਕਰੋ',
    cancelling: 'ਰੱਦ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    confirmCancelBooking: 'ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਇਹ ਬੁਕਿੰਗ ਰੱਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ? ਇਹ ਸਲਾਟ ਹੋਰ ਕਿਸਾਨਾਂ ਲਈ ਉਪਲਬਧ ਹੋ ਜਾਵੇਗਾ।',
  },

  ta: {
    // Navbar
    kisanMandi: 'உழவர் மண்டி',
    eProcurement: 'மின் கொள்முதல்',
    deptSubtitle: 'நுகர்வோர் விவகாரங்கள் துறை • ஸ்மார்ட் கொள்முதல் தளம்',
    registeredFarmer: 'பதிவுசெய்த உழவர்',
    farmer: 'உழவர்',
    signOut: 'வெளியேறு',
    selectLanguage: 'மொழி',

    // Farmer Login & Registration
    backToHome: 'முகப்புக்குத் திரும்பு',
    kisanPortal: 'உழவர் போர்டல்',
    farmerSignInTitle: 'உழவர் உள்நுழைவு',
    farmerSignInSubtitle: 'பதிவுசெய்த கைப்பேசி எண் மற்றும் ஓடிபி மூலம் பாதுகாப்பாக உள்நுழைக',
    farmerRegisterTitle: 'புதிய உழவர் பதிவு',
    farmerRegisterSubtitle: 'மண்டி முன்பதிவு மற்றும் நேரடி குறைந்தபட்ச ஆதரவு விலை பெற ஒருமுறை பதிவு செய்க',
    tabSignIn: 'உழவர் உள்நுழைவு (OTP)',
    tabRegister: 'புதிய உழவர் பதிவு',
    mobileNumberLabel: 'கைப்பேசி எண்',
    mobileNumberPlaceholder: 'எ.கா. 9876543210',
    mobileNumberHelp: 'உங்கள் பிஎம்-கிசான் அல்லது மண்டிக் கணக்குடன் இணைக்கப்பட்ட 10 இலக்க எண்ணை உள்ளிடுக.',
    sendLoginOtp: 'OTP அனுப்புக',
    sendingOtp: 'OTP அனுப்பப்படுகிறது...',
    enterOtpLabel: '6 இலக்க OTP உள்ளிடுக',
    changeNumber: 'எண் மாற்றுக',
    verifyAndSignIn: 'சரிபார்த்து உள்நுழைக',
    verifying: 'சரிபார்க்கப்படுகிறது...',
    resendOtp: 'OTP வரவில்லையா? மீண்டும் அனுப்புக',
    simulatedSmsCode: 'மாதிரி SMS குறியீடு',
    autoFilled: 'தானாக நிரப்பப்பட்டது',
    fullNameLabel: 'முழுப் பெயர்',
    fullNamePlaceholder: 'எ.கா. சுந்தரம் பழனி',
    villageDistrictLabel: 'கிராமம் / மாவட்டம்',
    villageDistrictPlaceholder: 'எ.கா. ஆலங்குளம், தென்காசி',
    landRecordLabel: 'பட்டா / சிட்டா எண்',
    landRecordPlaceholder: 'எ.கா. KH-45892/2024',
    bankAccountLabel: 'DBT வங்கி கணக்கு எண்',
    bankAccountPlaceholder: 'எ.கா. 123456789012',
    registerAndContinue: 'பதிவுசெய்து தொடர்க',
    registering: 'பதிவு செய்யப்படுகிறது...',
    loginGovFooter: 'நுகர்வோர் விவகாரங்கள், உணவு மற்றும் பொது விநியோக அமைச்சகம் • நேரடி உழவர் போர்டல்',
    validPhoneError: 'சரியான 10 இலக்க கைப்பேசி எண்ணை உள்ளிடுக.',
    farmerNotFoundError: 'இந்த எண்ணில் உழவர் எவரும் பதிவு செய்யப்படவில்லை. கீழே "புதிய உழவர் பதிவு" என்பதைத் தேர்வு செய்க.',
    otpSentSuccess: '+91 {phone} எண்ணிற்கு OTP அனுப்பப்பட்டது. 6 இலக்கக் குறியீட்டை உள்ளிடுக.',
    validOtpError: 'சரியான 6 இலக்க OTP குறியீட்டை உள்ளிடுக.',
    signInSuccess: 'வெற்றிகரமாக உள்நுழைந்தது! உழவர் கட்டுப்பாட்டு பலகைக்குச் செல்கிறது...',
    registerRequiredFields: 'உங்கள் பெயர் மற்றும் கைப்பேசி எண் இரண்டையும் உள்ளிடுக.',
    registeredSuccess: 'உழவர் பதிவு வெற்றிகரமாக முடிந்தது! கட்டுப்பாட்டு பலகைக்குச் செல்கிறது...',
    alreadyRegisteredPhone: 'இந்த கைப்பேசி எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. மேலே "உழவர் உள்நுழைவு" தேர்வு செய்க.',

    // Farmer Home
    kisanDashboard: 'உழவர் கட்டுப்பாட்டு பலகை',
    welcomeGreeting: 'வணக்கம்',
    homeSubtitle: 'உங்கள் கொள்முதல் வருகைகளைத் திட்டமிடுங்கள், நெரிசலைத் தவிர்க்கவும், உங்கள் வங்கிக் கணக்கில் நேரடி MSP தொகையைப் பெறவும்.',
    landRecordKhasra: 'பட்டா / நில ஆவணம்',
    verifiedLand: 'சரிபார்க்கப்பட்ட நிலம்',
    dbtBankLinked: 'DBT வங்கி இணைப்பு',
    active: 'செயலில் உள்ளது',
    smsSimulationTitle: 'மாதிரி SMS அறிவிப்பு (DoCA-GOV)',
    smsDeliveredTo: '{phone} எண்ணிற்கு அனுப்பப்பட்டது • நேரடி வரிசை டோக்கன்',
    footerHackathon: 'ஸ்மார்ட் இந்தியா ஹேக்கத்தான் 2024 • நுகர்வோர் விவகாரங்கள், உணவு மற்றும் பொது விநியோக அமைச்சகம்',
    footerPlatform: 'ஸ்மார்ட் தானியங்கு மற்றும் நிகழ்நேரக் கொள்முதல் தளம்',

    // Live Queue Tracker
    radarCompleted: 'எடை நிறைவு & ஏற்றுக்கொள்ளப்பட்டது',
    radarInYard: 'நேரடி கொள்முதல் கள ரேடார்',
    radarPreArrival: 'வருகைக்கு முந்தைய டோக்கன் ரேடார்',
    mandiCenterDefault: 'மண்டி கொள்முதல் மையம்',
    completedTokenPrefix: 'முடிந்த டோக்கன்: ',
    inYardTokenPrefix: 'களத்தில் உள்ள டோக்கன்: ',
    advanceTokenPrefix: 'முன்பதிவு டோக்கன்: ',
    updated: 'புதுப்பிக்கப்பட்டது',
    refreshQueue: 'வரிசையைப் புதுப்பி',
    activeTokensNotice: 'உங்களிடம் {count} செயலில் உள்ள டோக்கன்கள் உள்ளன:',
    weighedStatus: 'எடை போடப்பட்டது',
    inYardStatus: 'களத்தில்',
    bookedStatus: 'முன்பதிவு',

    // Radar Cards - Scenario 1: Completed
    weighbridgeScale1: 'மின்னணு எடை மேடை #1',
    weighedDone: 'எடை நிறைவு',
    quintals: 'குவிண்டால்',
    kg: 'கிலோ',
    produceWeighedVerified: 'பயிர் எடை சரிபார்க்கப்பட்டது',
    qualityGrade: 'தர வகை',
    officialMsp: 'அரசு MSP விலை',
    totalMspPayout: 'மொத்த MSP கொடுப்பனவு',
    dbtDisbursed: 'DBT மூலம் செலுத்தப்பட்டது',
    dbtQueued: 'DBT வரிசையில் உள்ளது',
    dbtPaidDesc: 'ஆதார் DBT மூலம் உங்கள் வங்கிக் கணக்கில் நேரடியாகப் பணம் செலுத்தப்பட்டது.',
    dbtQueuedDesc: 'பணம் செலுத்துதல் தொடங்கப்பட்டது. 24-48 மணிநேரத்திற்குள் உங்கள் வங்கிக் கணக்கில் வரவு வைக்கப்படும்.',

    // Radar Cards - Scenario 2: In Yard
    nowServingScale1: 'எடை மேடை #1 இல் தற்போது எடை போடப்படுகிறது',
    scaleServingBadge: 'எடை மேடை',
    scaleOpen: 'எடை மேடை காலியாக உள்ளது',
    scaleTractorPositioned: 'டிராக்டர் தற்போது மின்னணு எடை மேடையில் நிறுத்தப்பட்டுள்ளது',
    scaleOpenReady: 'எடை மேடை காலியாக உள்ளது, அடுத்த வாகனத்திற்குத் தயார்',
    inYardPosition: 'கள வரிசை நிலை',
    yourTurnNow: 'இப்போது உங்கள் முறை!',
    queuePos: 'வரிசை எண் #{pos}',
    checkedInAtGate: 'நுழைவாயிலில் பதிவு செய்யப்பட்டது',
    driveScaleNow: 'உங்கள் டிராக்டரை உடனே எடை மேடை #1க்கு ஓட்டிச் செல்லவும்!',
    tractorsAheadYard: 'கள வரிசையில் உங்களுக்கு முன்னால் {count} டிராக்டர்கள் உள்ளன',
    gateVerifiedSync: 'நுழைவு சரிபார்க்கப்பட்டது • எடை மேடைக்கு அறிவிக்கப்படுகிறது...',

    // Radar Cards - Scenario 3: Pre-Arrival
    mandiScaleServing: 'மண்டி எடை மேடை #1 தற்போதைய நிலை',
    scaleOpenHome: 'மேடை காலியாக உள்ளது',
    processingNow: 'எடை போடுதல் நடக்கிறது',
    tractorsLinedUpYard: 'மண்டி வளாகத்தில் தற்போது {count} டிராக்டர்கள் வரிசையில் உள்ளன.',
    yourAdvanceBooking: 'உங்கள் முன்பதிவு',
    nextInTurn: 'அடுத்த முறை உங்களுடையது',
    tokensAheadPreArrival: 'உங்களுக்கு முன்னால் {count} டோக்கன்கள் உள்ளன',
    estimatedScaleTurn: 'எதிர்பார்க்கப்படும் எடை நேரம் ~{time} ({hours}மணி {mins}நிமி)',
    tomorrowLabel: 'நாளை',
    scheduledSlotConfirmed: 'திட்டமிடப்பட்ட ஸ்லாட் உறுதிசெய்யப்பட்டது',
    scheduledForTomorrow: 'நாளை திட்டமிடப்பட்டது',
    scheduledForDate: '{date} க்கு திட்டமிடப்பட்டது',
    gateOpensTomorrowDesc: 'கேட் பாதுகாப்பு செக்-இன் நாளை காலை 9:00 மணிக்கு திறக்கப்படும்.',
    futureBookingNoticeTitle: '{date} அன்று {time} மணிக்கு ஸ்லாட் உறுதிசெய்யப்பட்டது',
    futureBookingNoticeBody: 'தயவுசெய்து உங்கள் சரக்கு வாகனம் மற்றும் நில ஆவணங்களுடன் {date} அன்று {center} ஐ அடையவும். நேரடி வரிசை ரேடார் நாளை காலை தானாகவே செயல்படும்.',
    step2ArriveTomorrow: '{date} அன்று {time} மணிக்கு வருக',
    gateCheckInPending: 'கேட் செக்-இன் நிலுவையில் உள்ளது',
    turnNumberLabel: 'முறை #{num}',
    estimatedScaleTurnTime: 'எதிர்பார்க்கப்படும் எடை நேரம்',
    procurementHistory: 'கொள்முதல் வரலாறு',
    viewWeighedTokens: 'எடை ரசீதுகள்',
    weighedTokensModalTitle: 'எடை ரசீதுகள் மற்றும் கட்டண நிலை',
    weighedTokensModalSubtitle: 'அதிகாரப்பூர்வ எடை மேடை பதிவுகள் மற்றும் நேரடி வங்கி பரிமாற்ற (DBT) நிலை',
    noWeighedTokensYet: 'இதுவரை எடை போடப்பட்ட டோக்கன்கள் இல்லை',
    noWeighedTokensDesc: 'மண்டி எடை மேடை #1 இல் உங்கள் விளைபொருள் எடை போடப்பட்ட பிறகு, சரிபார்க்கப்பட்ட எடை ரசீது மற்றும் DBT பணம் செலுத்தும் பதிவு இங்கே தோன்றும்.',
    weighedOnDate: 'எடை போடப்பட்ட தேதி',
    scheduledGateArrival: 'வாயில் வருகை நேரம்',
    futureStaggeredNotice: 'பாதுகாப்பு செக்-இன் செய்ய சுமார் ~{arrivalTime}க்குள் மண்டி நுழைவாயிலை அடையவும். எடை மேடையில் உங்கள் எதிர்பார்க்கப்படும் நேரம் ~{turnTime} (முறை #{turn}).',
    history: 'வரலாறு',
    closeModal: 'மூடுக',

    // Notices
    lunchBreakTitle: 'மண்டி மதிய உணவு இடைவேளை (மதியம் 1:00 – 2:00)',
    lunchBreakDesc: 'அலுவலர் மதிய உணவுக்காக எடை மேடை தற்காலிகமாக நிறுத்தப்பட்டுள்ளது. மதியம் 2:00 மணிக்கு மீண்டும் தொடங்கும்.',
    resumesAtTwoPm: 'மதியம் 2:00 மணிக்கு மீண்டும் தொடங்கும்',
    gateClosedTitle: 'இன்றைய கொள்முதல் நுழைவு நிறைவுற்றது (மாலை 5:00)',
    gateClosedInYardDesc: 'உங்கள் டிராக்டர் வளாகத்தினுள் உள்ளது. உள்ளே உள்ள அனைத்து வாகனங்களுக்கும் எடை போடப்படும்.',
    gateClosedHomeDesc: 'இன்றைய நுழைவு நிறைவடைந்தது. முன்பதிவு செய்யப்படாத டோக்கன்கள் காலாவதியாகின. நாளைக்கு புதிய இடம் முன்பதிவு செய்க.',
    gateClosedBadge: 'நுழைவு மூடப்பட்டது (மாலை 5:00)',

    // Advisories
    congratsWeighedTitle: 'டோக்கன் {token} எடை நிறைவடைந்தது!',
    congratsWeighedBody: 'உங்கள் {crop} எடை சரிபார்க்கப்பட்டு ஏற்றுக்கொள்ளப்பட்டது. மொத்த MSP தொகை ₹{amount} உங்கள் வங்கிக் கணக்கிற்கு{bankSuffix} DBT மூலம் செலுத்தப் பதிவு செய்யப்பட்டுள்ளது.',
    bankAccountEnding: ' (கடைசி 4 இலக்கம் ••••{last4})',
    yardTurnNowTitle: 'டோக்கன் {token} - இப்போது உங்கள் முறை!',
    yardTurnNowBody: 'உங்கள் டிராக்டரை உடனே எடை மேடை #1க்கு ஓட்டிச் செல்லவும். அலுவலர் தயாராக உள்ளார்.',
    yardGetReadyTitle: 'டோக்கன் {token} - தயாராக இருங்கள்!',
    yardGetReadyBody: 'உங்களுக்கு முன்னால் {count} டிராக்டர்கள் மட்டுமே உள்ளன. டிராக்டரை இயக்கி எடை மேடைக்கு அருகில் இருக்கவும்.',
    yardRestShedTitle: 'உழவர் ஓய்வறையில் ஓய்வெடுக்கவும்!',
    yardRestShedBody: 'களத்தில் உங்களுக்கு முன்னால் {count} டிராக்டர்கள் உள்ளன. 5 டிராக்டர்கள் இருக்கும்போது நாங்கள் உங்களுக்கு அறிவிப்போம்.',
    preArrivalUrgentTitle: 'டோக்கன் {token} முறை நெருங்கிவிட்டது! நுழைவாயிலுக்கு வரவும்',
    preArrivalUrgentBody: 'உங்களுக்கு முன்னால் {count} டோக்கன்கள் மட்டுமே உள்ளன. சரிபார்ப்பிற்கு உடனே {center} வாயில் #1க்கு வரவும்.',
    preArrivalRelaxTitle: 'வீட்டில் ஓய்வெடுக்கவும்: உங்கள் நேரம் சுமார் ~{time}',
    preArrivalRelaxBody: 'எடை மேடையில் டோக்கன் {servingToken} நடக்கிறது. உங்களுக்கு முன்னால் {ahead} டோக்கன்கள் உள்ளன. உங்கள் முறைக்கு 30 நிமிடங்கள் முன்பு (~{gateTime}க்குள்) மண்டிக்கு வரவும்.',
    earlierSlots: 'முந்தைய டோக்கன்கள்',
    suggestedGateArrival: 'பரிந்துரைக்கப்பட்ட வருகை நேரம்',
    immediately: 'உடனடியாக',

    // Traffic & Velocity
    yardTrafficTitle: 'மண்டி கள போக்குவரத்து ({center})',
    fastFlow: 'சீரான வேகம்',
    yardTrafficDesc: 'கள வரிசையில் {yardCount} டிராக்டர்கள் • இன்று {bookedCount} முன்பதிவுகள் • சராசரி எடை நேரம்: ~{avgMin} நிமிடங்கள்',
    yardWaitTimeLabel: 'களத்தில் காத்திருக்கும் நேரம்',
    estimatedTimeToTurnLabel: 'எடை போடும் வரை உத்தேச நேரம்',
    zeroMinsProcured: '0 நிமிடங்கள் (கொள்முதல் முடிந்தது)',
    zeroMinsAtScale: '0 நிமிடங்கள் (மேடையில் உள்ளது)',
    approxMinutes: '~{mins} நிமிடங்கள்',
    approxMinsWithTime: '~{mins} நிமிடங்கள் (~{time})',

    // 5-Step Journey Stepper
    procurementLifecycle: 'டோக்கன் {token} கொள்முதல் & கொடுப்பனவு நிலை',
    step1Title: 'முன்பதிவு முடிந்தது',
    step1Subtitle: 'உறுதி செய்யப்பட்டது',
    step2Title: 'வாயில் சரிபார்ப்பு',
    step2EntryDone: 'நுழைவு முடிந்தது',
    step2CheckedIn: 'மண்டியில் உள்ளீர்கள்',
    step2ReachGateNow: 'உடனே வாயிலுக்கு வரவும்!',
    step2ArriveBy: '~{time}க்குள் வருக',
    step3Title: 'எடை மேடை',
    step3WeighingDone: 'எடை நிறைவு',
    step3NowAtScale1: 'மேடை #1 இல் உள்ளது',
    step3QueueNum: 'வரிசை எண் #{pos}',
    step3InLine: 'வரிசையில்',
    step4Title: 'பயிர் எடை நிறைவு',
    step4JFormIssued: 'ஜே-படிவம் சீட்டு வழங்கப்பட்டது',
    step4AwaitingScale: 'எடைக்குக் காத்திருக்கிறது',
    step5Title: 'நேரடி வங்கி செலுத்துகை',
    step5Credited: 'வங்கிக்கு வரவு வைக்கப்பட்டது',
    step5InTransit: 'DBT செலுத்தப்படுகிறது',
    step5DirectDeposit: 'நேரடி வங்கி பரிமாற்றம்',
    stepNum: 'படி {num}',

    // Slot Booking
    smartSlotAllocation: 'ஸ்மார்ட் முன்பதிவு ஒதுக்கீடு',
    bookMandiArrivalSlot: 'மண்டி வருகை முன்பதிவு செய்க',
    slotBookingSubtitle: 'வரிசையில் காத்திருப்பதைத் தவிர்க்கவும் டிஜிட்டல் டோக்கன் பெறவும் வருகை நேரத்தை முன்பதிவு செய்க',
    slotConfirmed: 'முன்பதிவு உறுதியானது!',
    yourToken: 'உங்கள் டோக்கன்:',
    smsSimulatedHint: 'SMS உறுதிப்படுத்தல் அனுப்பப்பட்டுள்ளது. வருகையின் போது மண்டி கவுண்டரில் இந்த டோக்கனைக் காட்டவும்.',
    bookAnotherSlot: 'மற்றொரு முன்பதிவு செய்க',
    mandiCenterLabel: 'மண்டி கொள்முதல் மையம்',
    loadingCenters: 'மையங்கள் ஏற்றப்படுகின்றன...',
    noCentersConfigured: 'கணினியில் மையங்கள் எதுவும் இல்லை.',
    produceCropLabel: 'பயிர் வகை',
    arrivalDateLabel: 'வருகை தேதி',
    availableSlotsForCrop: '{crop}க்கான முன்பதிவு நேரங்கள்',
    slotsAvailableCount: '{count} முன்பதிவுகள் உள்ளன',
    slotSingular: 'இடம்',
    slotPlural: 'இடங்கள்',
    intakeCapacityFullTitle: 'இன்றைய கொள்முதல் கொள்ளளவு நிறைவடைந்தது',
    intakeCapacityFullDesc: 'இன்றைய வரிசை மாலை 5:00 மணிக்கு மேல் நீள்கிறது. இன்று மேலும் முன்பதிவு செய்ய முடியாது.',
    switchToTomorrow: 'நாளைக்கு முன்பதிவு செய்க',
    checkingSlotAvailability: 'நிகழ்நேரக் கிடைக்கும் தன்மை சரிபார்க்கப்படுகிறது...',
    noOpenSlotsFound: 'இந்த தேதி மற்றும் பயிருக்கு முன்பதிவு இல்லை',
    noOpenSlotsDesc: 'மண்டி நிர்வாகம் இந்த தேதிக்குக் கொள்முதல் நேரத்தை இன்னும் திட்டமிடவில்லை. வேறு தேதி அல்லது பயிரைத் தேர்ந்தெடுக்கவும்.',
    intakeClosedCutoff: 'நுழைவு நிறைவுற்றது (மாலை 5 மணி)',
    slotFullBadge: 'முழுமை',
    seatsLeftBadge: '{count} இடங்கள் உள்ளன',
    capacityBookedText: 'கொள்ளளவு: {booked} / {capacity} உழவர்கள்',
    reservingSeat: 'இடம் முன்பதிவு செய்யப்படுகிறது...',
    intakeFullBtn: 'கொள்ளளவு நிறைவு (மாலை 5:00)',
    slotFullBtn: 'இடம் முடிந்தது',
    bookThisSlotBtn: 'இடத்தை முன்பதிவு செய்க',

    // Farmer History
    myTokensPassbook: 'எனது டோக்கன்கள் & பாஸ்புக்',
    historySubtitle: 'செயலில் உள்ள டோக்கன்கள், எடை நிலை மற்றும் DBT வங்கிப் பண நிலையைப் பார்க்கவும்',
    refreshHistory: 'வரலாற்றைப் புதுப்பி',
    loadingPassbook: 'டிஜிட்டל பாஸ்புக் ஏற்றப்படுகிறது...',
    noHistoryYet: 'முன்பதிவு வரலாறு எதுவும் இல்லை',
    noHistoryDesc: 'நீங்கள் இதுவரை மண்டி முன்பதிவு எதுவும் செய்யவில்லை. உங்கள் முதல் முன்பதிவைச் செய்ய மேலே உள்ள பகுதியைப் பயன்படுத்தவும்.',
    statusBooked: 'முன்பதிவு செய்யப்பட்டது',
    statusCheckedIn: 'மண்டி வரிசையில்',
    statusCompleted: 'கொள்முதல் முடிந்தது',
    statusCancelled: 'ரத்து செய்யப்பட்டது',
    paymentAwaitingWeighing: 'எடைக்குக் காத்திருக்கிறது',
    paymentPaidViaDbt: 'DBT மூலம் செலுத்தப்பட்டது',
    paymentProcessing: 'செயல்பாட்டில் உள்ளது',
    paymentPending: 'பணம் நிலுவையில்',
    tokenLabel: 'டோக்கன்',
    atTime: 'நேரம்',
    cropLabel: 'பயிர்',
    cancelSlot: 'முன்பதிவை ரத்து செய்க',
    cancelling: 'ரத்து செய்யப்படுகிறது...',
    confirmCancelBooking: 'இந்த முன்பதிவை நிச்சயமாக ரத்து செய்ய விரும்புகிறீர்களா? இந்த இடம் மற்ற உழவர்களுக்கு வழங்கப்படும்.',
  },
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('farmer_lang') || 'en'
  })

  const setLanguage = (langCode) => {
    if (translations[langCode]) {
      setLanguageState(langCode)
      localStorage.setItem('farmer_lang', langCode)
    }
  }

  // Translation helper with template variable replacement: {varName}
  const t = (key, params = {}) => {
    const dict = translations[language] || translations.en
    let str = dict[key] || translations.en[key] || key

    if (params && typeof params === 'object') {
      Object.keys(params).forEach((placeholder) => {
        str = str.replace(new RegExp(`\\{${placeholder}\\}`, 'g'), params[placeholder] ?? '')
      })
    }
    return str
  }

  // Localized Crop Name lookup
  const getCropName = (cropKey) => {
    const crop = CROPS_DATA.find((c) => c.key.toLowerCase() === (cropKey || '').toLowerCase())
    if (!crop) return cropKey
    return crop.names[language] || crop.names.en || cropKey
  }

  // Localized Status Badge
  const getStatusLabel = (status) => {
    switch (status) {
      case 'booked':
        return t('statusBooked')
      case 'checked_in':
        return t('statusCheckedIn')
      case 'completed':
        return t('statusCompleted')
      case 'cancelled':
        return t('statusCancelled')
      default:
        return status
    }
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        getCropName,
        getStatusLabel,
        languages: LANGUAGES,
        crops: CROPS_DATA,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return ctx
}

export default LanguageContext
